[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
known_third_party = ['sanic','loguru','requests']
known_first_party = ['utils', 'config']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.black]
line_length = 99
